package org.freelift5.app.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color
import org.freelift5.app.theme.AppThemeId
import org.freelift5.app.theme.ThemePreferences

data class AppThemeDefinition(
    val id: AppThemeId,
    val name: String,
    val description: String,
    val swatches: List<Color>,
    val colorScheme: ColorScheme,
) {
    val isDark: Boolean get() = id.isDark
}

object ThemeCatalog {
    val all: List<AppThemeDefinition> = listOf(
        solarizedLight(),
        fieldManual(),
        poolTile(),
        solarizedDark(),
        foundry(),
    )

    val lightThemes: List<AppThemeDefinition> = all.filterNot(AppThemeDefinition::isDark)
    val darkThemes: List<AppThemeDefinition> = all.filter(AppThemeDefinition::isDark)

    private val byId = all.associateBy(AppThemeDefinition::id)

    fun get(id: AppThemeId): AppThemeDefinition = byId.getValue(id)

    fun resolve(
        preferences: ThemePreferences,
        systemDark: Boolean,
    ): AppThemeDefinition = get(preferences.resolvedTheme(systemDark))
}

private fun solarizedLight() = AppThemeDefinition(
    id = AppThemeId.SOLARIZED_LIGHT,
    name = "Solarized Light",
    description = "Warm paper with ocean blue, teal, and amber signals.",
    swatches = colors(0xFFFDF6E3, 0xFF006A94, 0xFF376E68, 0xFF765F00),
    colorScheme = scheme(
        primary = 0xFF006A94,
        onPrimary = 0xFFFFFFFF,
        primaryContainer = 0xFFC6E7F2,
        onPrimaryContainer = 0xFF002B36,
        inversePrimary = 0xFF7DD3F0,
        secondary = 0xFF376E68,
        onSecondary = 0xFFFFFFFF,
        secondaryContainer = 0xFFCCE8E2,
        onSecondaryContainer = 0xFF0B302D,
        tertiary = 0xFF765F00,
        onTertiary = 0xFFFFFFFF,
        tertiaryContainer = 0xFFF4E1A1,
        onTertiaryContainer = 0xFF2A2100,
        background = 0xFFFDF6E3,
        onBackground = 0xFF002B36,
        surface = 0xFFFDF6E3,
        onSurface = 0xFF002B36,
        surfaceVariant = 0xFFE4DDCA,
        onSurfaceVariant = 0xFF465A60,
        inverseSurface = 0xFF002B36,
        inverseOnSurface = 0xFFFDF6E3,
        error = 0xFF9B1C1C,
        onError = 0xFFFFFFFF,
        errorContainer = 0xFFFFDAD6,
        onErrorContainer = 0xFF410002,
        outline = 0xFF657B83,
        outlineVariant = 0xFF73858A,
        surfaceBright = 0xFFFFFBED,
        surfaceDim = 0xFFDED7C4,
        surfaceContainerLowest = 0xFFFFFFFF,
        surfaceContainerLow = 0xFFF8F1DE,
        surfaceContainer = 0xFFF1EAD7,
        surfaceContainerHigh = 0xFFEAE3D0,
        surfaceContainerHighest = 0xFFE4DDCA,
        primaryFixed = 0xFFC6E7F2,
        primaryFixedDim = 0xFF7DC4DD,
        onPrimaryFixed = 0xFF002B36,
        onPrimaryFixedVariant = 0xFF174B5D,
        secondaryFixed = 0xFFCCE8E2,
        secondaryFixedDim = 0xFF91C9C0,
        onSecondaryFixed = 0xFF0B302D,
        onSecondaryFixedVariant = 0xFF254F4B,
        tertiaryFixed = 0xFFF4E1A1,
        tertiaryFixedDim = 0xFFD5BD6C,
        onTertiaryFixed = 0xFF2A2100,
        onTertiaryFixedVariant = 0xFF594900,
    ),
)

private fun fieldManual() = AppThemeDefinition(
    id = AppThemeId.FIELD_MANUAL,
    name = "Field Manual",
    description = "Kraft paper, olive ink, worn leather, and safety orange.",
    swatches = colors(0xFFF3E9CF, 0xFF46512F, 0xFF6B5844, 0xFFA44323),
    colorScheme = scheme(
        primary = 0xFF46512F,
        onPrimary = 0xFFFFFFFF,
        primaryContainer = 0xFFDCE5BE,
        onPrimaryContainer = 0xFF20280F,
        inversePrimary = 0xFFB9C794,
        secondary = 0xFF6B5844,
        onSecondary = 0xFFFFFFFF,
        secondaryContainer = 0xFFE9D6C2,
        onSecondaryContainer = 0xFF2B1A0C,
        tertiary = 0xFFA44323,
        onTertiary = 0xFFFFFFFF,
        tertiaryContainer = 0xFFFFDCCB,
        onTertiaryContainer = 0xFF3B0A00,
        background = 0xFFF3E9CF,
        onBackground = 0xFF28251C,
        surface = 0xFFF3E9CF,
        onSurface = 0xFF28251C,
        surfaceVariant = 0xFFE2D6BA,
        onSurfaceVariant = 0xFF514A3B,
        inverseSurface = 0xFF28251C,
        inverseOnSurface = 0xFFF3E9CF,
        error = 0xFF9B1C1C,
        onError = 0xFFFFFFFF,
        errorContainer = 0xFFFFDAD6,
        onErrorContainer = 0xFF410002,
        outline = 0xFF776F5D,
        outlineVariant = 0xFF8A816F,
        surfaceBright = 0xFFFFF8E7,
        surfaceDim = 0xFFD8CDB2,
        surfaceContainerLowest = 0xFFFFFBF0,
        surfaceContainerLow = 0xFFEFE5CB,
        surfaceContainer = 0xFFE9DFC5,
        surfaceContainerHigh = 0xFFE5DAC0,
        surfaceContainerHighest = 0xFFE2D6BA,
        primaryFixed = 0xFFDCE5BE,
        primaryFixedDim = 0xFFB9C794,
        onPrimaryFixed = 0xFF20280F,
        onPrimaryFixedVariant = 0xFF3E4928,
        secondaryFixed = 0xFFE9D6C2,
        secondaryFixedDim = 0xFFCDB9A4,
        onSecondaryFixed = 0xFF2B1A0C,
        onSecondaryFixedVariant = 0xFF584631,
        tertiaryFixed = 0xFFFFDCCB,
        tertiaryFixedDim = 0xFFF0A581,
        onTertiaryFixed = 0xFF3B0A00,
        onTertiaryFixedVariant = 0xFF7E2E14,
    ),
)

private fun poolTile() = AppThemeDefinition(
    id = AppThemeId.POOL_TILE,
    name = "Pool Tile",
    description = "Cool porcelain with deep teal, slate blue, and rose markings.",
    swatches = colors(0xFFF2F7F4, 0xFF006B73, 0xFF405D78, 0xFFA63D4C),
    colorScheme = scheme(
        primary = 0xFF006B73,
        onPrimary = 0xFFFFFFFF,
        primaryContainer = 0xFFA3EFF2,
        onPrimaryContainer = 0xFF002022,
        inversePrimary = 0xFF78D8DC,
        secondary = 0xFF405D78,
        onSecondary = 0xFFFFFFFF,
        secondaryContainer = 0xFFD4E4FA,
        onSecondaryContainer = 0xFF10283D,
        tertiary = 0xFFA63D4C,
        onTertiary = 0xFFFFFFFF,
        tertiaryContainer = 0xFFFFD9DD,
        onTertiaryContainer = 0xFF3F0010,
        background = 0xFFF2F7F4,
        onBackground = 0xFF10201E,
        surface = 0xFFF2F7F4,
        onSurface = 0xFF10201E,
        surfaceVariant = 0xFFDDE9E5,
        onSurfaceVariant = 0xFF405B56,
        inverseSurface = 0xFF10201E,
        inverseOnSurface = 0xFFF2F7F4,
        error = 0xFFA51D2D,
        onError = 0xFFFFFFFF,
        errorContainer = 0xFFFFDADD,
        onErrorContainer = 0xFF410007,
        outline = 0xFF657B76,
        outlineVariant = 0xFF738985,
        surfaceBright = 0xFFFAFFFC,
        surfaceDim = 0xFFD4DEDA,
        surfaceContainerLowest = 0xFFFFFFFF,
        surfaceContainerLow = 0xFFEDF3F0,
        surfaceContainer = 0xFFE7EFEB,
        surfaceContainerHigh = 0xFFE2EBE7,
        surfaceContainerHighest = 0xFFDDE9E5,
        primaryFixed = 0xFFA3EFF2,
        primaryFixedDim = 0xFF78D8DC,
        onPrimaryFixed = 0xFF002022,
        onPrimaryFixedVariant = 0xFF005158,
        secondaryFixed = 0xFFD4E4FA,
        secondaryFixedDim = 0xFFB4C8E0,
        onSecondaryFixed = 0xFF10283D,
        onSecondaryFixedVariant = 0xFF334F69,
        tertiaryFixed = 0xFFFFD9DD,
        tertiaryFixedDim = 0xFFF3AEB7,
        onTertiaryFixed = 0xFF3F0010,
        onTertiaryFixedVariant = 0xFF842A3A,
    ),
)

private fun solarizedDark() = AppThemeDefinition(
    id = AppThemeId.SOLARIZED_DARK,
    name = "Solarized Dark",
    description = "Deep blue-green with cyan, amber, and violet signals.",
    swatches = colors(0xFF002B36, 0xFF2AA198, 0xFFB58900, 0xFF9C9FE8),
    colorScheme = scheme(
        primary = 0xFF2AA198,
        onPrimary = 0xFF002B36,
        primaryContainer = 0xFF0C5152,
        onPrimaryContainer = 0xFFB8F5EC,
        inversePrimary = 0xFF006A64,
        secondary = 0xFFB58900,
        onSecondary = 0xFF002B36,
        secondaryContainer = 0xFF5A4600,
        onSecondaryContainer = 0xFFFFE08A,
        tertiary = 0xFF9C9FE8,
        onTertiary = 0xFF16164F,
        tertiaryContainer = 0xFF41447A,
        onTertiaryContainer = 0xFFE3E1FF,
        background = 0xFF002B36,
        onBackground = 0xFFFDF6E3,
        surface = 0xFF073642,
        onSurface = 0xFFFDF6E3,
        surfaceVariant = 0xFF164A55,
        onSurfaceVariant = 0xFFD6E6E4,
        inverseSurface = 0xFFFDF6E3,
        inverseOnSurface = 0xFF002B36,
        error = 0xFFFFB4AB,
        onError = 0xFF690005,
        errorContainer = 0xFF93000A,
        onErrorContainer = 0xFFFFDAD6,
        outline = 0xFF93A1A1,
        outlineVariant = 0xFF7B9294,
        surfaceBright = 0xFF244F59,
        surfaceDim = 0xFF002B36,
        surfaceContainerLowest = 0xFF001E26,
        surfaceContainerLow = 0xFF052F3A,
        surfaceContainer = 0xFF0A3944,
        surfaceContainerHigh = 0xFF10434E,
        surfaceContainerHighest = 0xFF164A55,
        primaryFixed = 0xFFA5F2E9,
        primaryFixedDim = 0xFF2AA198,
        onPrimaryFixed = 0xFF002B36,
        onPrimaryFixedVariant = 0xFF002B36,
        secondaryFixed = 0xFFFFDF89,
        secondaryFixedDim = 0xFFB58900,
        onSecondaryFixed = 0xFF2A2100,
        onSecondaryFixedVariant = 0xFF2A2100,
        tertiaryFixed = 0xFFE3E1FF,
        tertiaryFixedDim = 0xFF9C9FE8,
        onTertiaryFixed = 0xFF16164F,
        onTertiaryFixedVariant = 0xFF16164F,
    ),
)

private fun foundry() = AppThemeDefinition(
    id = AppThemeId.FOUNDRY,
    name = "Foundry",
    description = "Charcoal steel with furnace orange, oxidized blue, and brass.",
    swatches = colors(0xFF171A1B, 0xFFE47A42, 0xFF8EB9C4, 0xFFD0AD58),
    colorScheme = scheme(
        primary = 0xFFE47A42,
        onPrimary = 0xFF2B0D00,
        primaryContainer = 0xFF5B280F,
        onPrimaryContainer = 0xFFFFDCCB,
        inversePrimary = 0xFF8C3A16,
        secondary = 0xFF8EB9C4,
        onSecondary = 0xFF062F37,
        secondaryContainer = 0xFF274951,
        onSecondaryContainer = 0xFFD1F3FC,
        tertiary = 0xFFD0AD58,
        onTertiary = 0xFF352900,
        tertiaryContainer = 0xFF574500,
        onTertiaryContainer = 0xFFFFE4A1,
        background = 0xFF171A1B,
        onBackground = 0xFFF3EEE6,
        surface = 0xFF1F2324,
        onSurface = 0xFFF3EEE6,
        surfaceVariant = 0xFF394042,
        onSurfaceVariant = 0xFFDCE3E4,
        inverseSurface = 0xFFF3EEE6,
        inverseOnSurface = 0xFF171A1B,
        error = 0xFFFFB4AB,
        onError = 0xFF690005,
        errorContainer = 0xFF93000A,
        onErrorContainer = 0xFFFFDAD6,
        outline = 0xFF9DA5A7,
        outlineVariant = 0xFF7B8385,
        surfaceBright = 0xFF454B4D,
        surfaceDim = 0xFF171A1B,
        surfaceContainerLowest = 0xFF101314,
        surfaceContainerLow = 0xFF1B1E1F,
        surfaceContainer = 0xFF242829,
        surfaceContainerHigh = 0xFF2E3334,
        surfaceContainerHighest = 0xFF394042,
        primaryFixed = 0xFFFFDCCB,
        primaryFixedDim = 0xFFE47A42,
        onPrimaryFixed = 0xFF2B0D00,
        onPrimaryFixedVariant = 0xFF2B0D00,
        secondaryFixed = 0xFFD1F3FC,
        secondaryFixedDim = 0xFF8EB9C4,
        onSecondaryFixed = 0xFF062F37,
        onSecondaryFixedVariant = 0xFF062F37,
        tertiaryFixed = 0xFFFFE4A1,
        tertiaryFixedDim = 0xFFD0AD58,
        onTertiaryFixed = 0xFF352900,
        onTertiaryFixedVariant = 0xFF352900,
    ),
)

@Suppress("LongParameterList")
private fun scheme(
    primary: Long,
    onPrimary: Long,
    primaryContainer: Long,
    onPrimaryContainer: Long,
    inversePrimary: Long,
    secondary: Long,
    onSecondary: Long,
    secondaryContainer: Long,
    onSecondaryContainer: Long,
    tertiary: Long,
    onTertiary: Long,
    tertiaryContainer: Long,
    onTertiaryContainer: Long,
    background: Long,
    onBackground: Long,
    surface: Long,
    onSurface: Long,
    surfaceVariant: Long,
    onSurfaceVariant: Long,
    inverseSurface: Long,
    inverseOnSurface: Long,
    error: Long,
    onError: Long,
    errorContainer: Long,
    onErrorContainer: Long,
    outline: Long,
    outlineVariant: Long,
    surfaceBright: Long,
    surfaceDim: Long,
    surfaceContainer: Long,
    surfaceContainerHigh: Long,
    surfaceContainerHighest: Long,
    surfaceContainerLow: Long,
    surfaceContainerLowest: Long,
    primaryFixed: Long,
    primaryFixedDim: Long,
    onPrimaryFixed: Long,
    onPrimaryFixedVariant: Long,
    secondaryFixed: Long,
    secondaryFixedDim: Long,
    onSecondaryFixed: Long,
    onSecondaryFixedVariant: Long,
    tertiaryFixed: Long,
    tertiaryFixedDim: Long,
    onTertiaryFixed: Long,
    onTertiaryFixedVariant: Long,
): ColorScheme = ColorScheme(
    primary = color(primary),
    onPrimary = color(onPrimary),
    primaryContainer = color(primaryContainer),
    onPrimaryContainer = color(onPrimaryContainer),
    inversePrimary = color(inversePrimary),
    secondary = color(secondary),
    onSecondary = color(onSecondary),
    secondaryContainer = color(secondaryContainer),
    onSecondaryContainer = color(onSecondaryContainer),
    tertiary = color(tertiary),
    onTertiary = color(onTertiary),
    tertiaryContainer = color(tertiaryContainer),
    onTertiaryContainer = color(onTertiaryContainer),
    background = color(background),
    onBackground = color(onBackground),
    surface = color(surface),
    onSurface = color(onSurface),
    surfaceVariant = color(surfaceVariant),
    onSurfaceVariant = color(onSurfaceVariant),
    surfaceTint = color(primary),
    inverseSurface = color(inverseSurface),
    inverseOnSurface = color(inverseOnSurface),
    error = color(error),
    onError = color(onError),
    errorContainer = color(errorContainer),
    onErrorContainer = color(onErrorContainer),
    outline = color(outline),
    outlineVariant = color(outlineVariant),
    scrim = Color.Black,
    surfaceBright = color(surfaceBright),
    surfaceDim = color(surfaceDim),
    surfaceContainer = color(surfaceContainer),
    surfaceContainerHigh = color(surfaceContainerHigh),
    surfaceContainerHighest = color(surfaceContainerHighest),
    surfaceContainerLow = color(surfaceContainerLow),
    surfaceContainerLowest = color(surfaceContainerLowest),
    primaryFixed = color(primaryFixed),
    primaryFixedDim = color(primaryFixedDim),
    onPrimaryFixed = color(onPrimaryFixed),
    onPrimaryFixedVariant = color(onPrimaryFixedVariant),
    secondaryFixed = color(secondaryFixed),
    secondaryFixedDim = color(secondaryFixedDim),
    onSecondaryFixed = color(onSecondaryFixed),
    onSecondaryFixedVariant = color(onSecondaryFixedVariant),
    tertiaryFixed = color(tertiaryFixed),
    tertiaryFixedDim = color(tertiaryFixedDim),
    onTertiaryFixed = color(onTertiaryFixed),
    onTertiaryFixedVariant = color(onTertiaryFixedVariant),
)

private fun color(value: Long): Color = Color(value)

private fun colors(vararg values: Long): List<Color> = values.map(::color)
